### PR TITLE
api docs

### PR DESCRIPTION
**Pull request by tanyagupta**
## Issue Number: 123
Testing API docs
## Issue Description:
Proposing format/style of API documentation 

### Summary of solution:
1. Using http://apidocjs.com
2. We can either use it just to generate the round of documentation and leave it at that (without integration) OR we can integrate it into project
3. Note all docs need to display the html is inside one folder
 index.html will display api documentation results 
Please let me know if you want to use this, and if so which approach (full integration - will need your help) or a simpler integration which means you will need the supporting files only and it will be a one off effort

### Can this issue be closed?
No
### Should any new issues be added as a result of this solution?
No. But if we go this route other documentation including the wiki may need to be updated as well for a similar look/feel
### Have you named your branch in a descriptive way? Remember to name your branch in a unique and descriptive manner in order to properly reflect the issue or feature.
Yes

### CODE REVIEW

**Comment by motosharpley** [comment]
Looks like a very cool utility! It's going to take me a bit to review the options but I will make my way through and get with you soon.

**Comment by motosharpley** [comment]
@tanyagupta I think I would be up for doing a full integration on this. It looks like we can create a custom template in order make things flow with the rest of the docs. I think a lot of our api has the docstrings that this is picking up we just need to go through and get it configured. We could also break out some smaller issues to tackle this if need be, I think learning to put together documentation is a great way to learn to use documentation so could a good learning exercise.

**Comment by tanyagupta** [comment]
Thanks @motosharpley. I would definitely be up for helping with that. So should we close the original issue #103 and open new ones for the above ? I would like to learn about apidocs myself

**Comment by tanyagupta** [comment]
Yes, sorry I meant #123. I will take a crack on expanding the description along the lines of our discussion. Hopefully it will make the process clearer to everyone, specially now we have more folks interested in this task.

**Pull request closed without merging**
